language: java
jdk:
  - openjdk8

env:
  global:
    - CODECOV_TOKEN = c94b61dd-a2a3-434f-bfda-a5679aaa2177
install: true

script: gradle build

before_install:
  - gradle clean

branches:
  only:
    - master